resources:
  - online_shop.yaml
  - ingress.yaml
  - oracledb_deployment.yml
patches:
  - path: deployment-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: stored-procedures-deployment
