[package]
org = "ballerinax"
name = "oracledb"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../native/build/libs/oracledb-native-@project.version@.jar"

[[platform.java11.dependency]]
path = "./lib/sql-native-@stdlib.sql.native.version@.jar"

[[platform.java11.dependency]]
path = "./lib/ojdbc8-@oracledb.driver.version@.jar"
scope = "testOnly"
