[package]
org = "ballerinax"
name = "oracledb"
version = "0.1.0"

[[dependency]]
org = "ballerina"
name = "sql"
version = "0.5.4"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "1.0.5"

[[platform.java11.dependency]]
path = "../oracledb-native/build/libs/oracledb-native-0.1.0-SNAPSHOT.jar"
groupId = "org.ballerinalang"
artifactId = "oracledb-native"
version = "0.1.0-SNAPSHOT"


[[platform.java11.dependency]]
path = "/home/gayal/Desktop/Project/Implementation/module-ballerinax-oracledb/oracledb-ballerina/build/target/jballerina-tools-2.0.0-Preview9-SNAPSHOT/repo/balo/ballerina/sql/0.5.4/platform/java11/sql-native-0.5.4-SNAPSHOT.jar"
groupId = "org.ballerinalang"
artifactId = "ballerina-sql"
version = "0.5.4-SNAPSHOT"


[[platform.java11.dependency]]
path = "./lib/ojdbc10.jar"
artafactId = "ojdbc10"
groupId = "com.oracle.database.jdbc"
scope = "testOnly"
version = "19.8.0.0"